#!/usr/bin/with-contenv bash
set -e

CONFIG_PATH="/usr/share/selkies/selkies-dashboard/src/selkies-paste-config.js"
RUNTIME_CONFIG_PATH="/usr/share/selkies/selkies-dashboard/src/selkies-runtime-config.js"

ENABLED_RAW="${SELKIES_PASTE_IMAGE:-true}"
MAX_BYTES_RAW="${SELKIES_PASTE_IMAGE_MAX_SIZE:-20971520}"
AUTO_PASTE_RAW="${SELKIES_PASTE_IMAGE_AUTO_PASTE:-true}"
DEFAULT_FRAMERATE_RAW="${SELKIES_DEFAULT_FRAMERATE:-48}"
DEFAULT_BINARY_CLIPBOARD_RAW="${SELKIES_DEFAULT_BINARY_CLIPBOARD:-true}"
DEFAULT_ENCODER_RAW="${SELKIES_DEFAULT_ENCODER:-x264enc}"
DEFAULT_USE_CPU_RAW="${SELKIES_DEFAULT_USE_CPU:-false}"
DEFAULT_H264_STREAMING_MODE_RAW="${SELKIES_DEFAULT_H264_STREAMING_MODE:-true}"
DEFAULT_USE_PAINT_OVER_QUALITY_RAW="${SELKIES_DEFAULT_USE_PAINT_OVER_QUALITY:-false}"
DEFAULT_H264_CRF_RAW="${SELKIES_DEFAULT_H264_CRF:-30}"
DEFAULT_DYNAMIC_LOW_LATENCY_RAW="${SELKIES_DYNAMIC_THROTTLE:-${SELKIES_DYNAMIC_LOW_LATENCY:-true}}"
DEFAULT_DYNAMIC_LOW_LATENCY_HOLD_RAW="${SELKIES_DYNAMIC_LOW_LATENCY_HOLD_MS:-15000}"
DEFAULT_DYNAMIC_THROTTLE_MODE_RAW="${SELKIES_DYNAMIC_THROTTLE_MODE:-idle-low-occupancy}"
DEFAULT_DYNAMIC_LOW_LATENCY_FPS_RAW="${SELKIES_DYNAMIC_LOW_LATENCY_FPS:-8}"
DEFAULT_DYNAMIC_LOW_LATENCY_CRF_RAW="${SELKIES_DYNAMIC_LOW_LATENCY_H264_CRF:-33}"
DEFAULT_DYNAMIC_LOW_LATENCY_SAMPLE_RAW="${SELKIES_DYNAMIC_LOW_LATENCY_SAMPLE_PERCENT:-91}"
DEFAULT_STREAM_WAIT_THRESHOLD_RAW="${SELKIES_STREAM_WAIT_THRESHOLD_MS:-35000}"
DEFAULT_STREAM_STALL_THRESHOLD_RAW="${SELKIES_STREAM_STALL_THRESHOLD_MS:-18000}"
DEFAULT_STREAM_STALL_RESTART_LIMIT_RAW="${SELKIES_STREAM_STALL_RESTART_LIMIT:-2}"
DEFAULT_STREAM_RECOVER_COOLDOWN_RAW="${SELKIES_STREAM_RECOVER_COOLDOWN_MS:-120000}"
DEFAULT_VIDEO_CORRUPTION_WATCHDOG_RAW="${SELKIES_VIDEO_CORRUPTION_WATCHDOG:-true}"
DEFAULT_VIDEO_SOFT_RECOVER_LIMIT_RAW="${SELKIES_VIDEO_SOFT_RECOVER_LIMIT:-2}"
DEFAULT_VIDEO_RECOVER_COOLDOWN_RAW="${SELKIES_VIDEO_RECOVER_COOLDOWN_MS:-120000}"
DEFAULT_PAGE_STALL_WATCHDOG_RAW="${SELKIES_PAGE_STALL_WATCHDOG:-true}"
DEFAULT_PAGE_STALL_THRESHOLD_RAW="${SELKIES_PAGE_STALL_THRESHOLD_MS:-45000}"
DEFAULT_PAGE_STALL_RELOAD_THRESHOLD_RAW="${SELKIES_PAGE_STALL_RELOAD_THRESHOLD_MS:-90000}"
DEFAULT_PAGE_STALL_COOLDOWN_RAW="${SELKIES_PAGE_STALL_COOLDOWN_MS:-300000}"
DEFAULT_RENDER_STALL_WATCHDOG_RAW="${SELKIES_RENDER_STALL_WATCHDOG:-true}"
DEFAULT_RENDER_STALL_THRESHOLD_RAW="${SELKIES_RENDER_STALL_THRESHOLD_MS:-12000}"
DEFAULT_RENDER_STALL_COOLDOWN_RAW="${SELKIES_RENDER_STALL_COOLDOWN_MS:-25000}"
DEFAULT_AUDIO_WATCHDOG_RAW="${SELKIES_AUDIO_WATCHDOG:-true}"
DEFAULT_AUDIO_START_INTERVAL_RAW="${SELKIES_AUDIO_START_INTERVAL_MS:-8000}"
DEFAULT_AUDIO_PACKET_STALL_RAW="${SELKIES_AUDIO_PACKET_STALL_MS:-15000}"
DEFAULT_IDLE_CLEANUP_MINUTES_RAW="${SELKIES_IDLE_CLEANUP_MINUTES:-20}"
DEFAULT_ADAPTIVE_SLEEP_IDLE_RAW="${SELKIES_ADAPTIVE_SLEEP_IDLE_SECONDS:-3600}"
LOCAL_LINK_OPEN_RAW="${SELKIES_LOCAL_LINK_OPEN:-true}"
LOCAL_LINK_POLL_INTERVAL_RAW="${SELKIES_LOCAL_LINK_POLL_INTERVAL_MS:-800}"
DRI_NODE_PATH="${DRI_NODE:-/dev/dri/renderD128}"

enabled_js="false"
case "${ENABLED_RAW,,}" in
  true|1|yes|on) enabled_js="true" ;;
  *) enabled_js="false" ;;
esac

max_bytes="${MAX_BYTES_RAW}"
if ! [[ "$max_bytes" =~ ^[0-9]+$ ]]; then
  max_bytes="20971520"
fi

auto_js="true"
case "${AUTO_PASTE_RAW,,}" in
  false|0|no|off) auto_js="false" ;;
  *) auto_js="true" ;;
esac

default_framerate="${DEFAULT_FRAMERATE_RAW}"
if ! [[ "$default_framerate" =~ ^[0-9]+$ ]] || [ "$default_framerate" -lt 1 ] || [ "$default_framerate" -gt 240 ]; then
  default_framerate="48"
fi

default_gamepad_js="false"

default_binary_clipboard_js="true"
case "${DEFAULT_BINARY_CLIPBOARD_RAW,,}" in
  false|0|no|off) default_binary_clipboard_js="false" ;;
  *) default_binary_clipboard_js="true" ;;
esac

default_use_cpu_js="false"
case "${DEFAULT_USE_CPU_RAW,,}" in
  false|0|no|off) default_use_cpu_js="false" ;;
  *) default_use_cpu_js="true" ;;
esac

default_h264_streaming_mode_js="true"
case "${DEFAULT_H264_STREAMING_MODE_RAW,,}" in
  false|0|no|off) default_h264_streaming_mode_js="false" ;;
  *) default_h264_streaming_mode_js="true" ;;
esac

default_use_paint_over_quality_js="false"
case "${DEFAULT_USE_PAINT_OVER_QUALITY_RAW,,}" in
  true|1|yes|on) default_use_paint_over_quality_js="true" ;;
  *) default_use_paint_over_quality_js="false" ;;
esac

default_h264_crf="${DEFAULT_H264_CRF_RAW}"
if ! [[ "$default_h264_crf" =~ ^[0-9]+$ ]] || [ "$default_h264_crf" -lt 5 ] || [ "$default_h264_crf" -gt 50 ]; then
  default_h264_crf="30"
fi

default_dynamic_low_latency_js="true"
case "${DEFAULT_DYNAMIC_LOW_LATENCY_RAW,,}" in
  false|0|no|off) default_dynamic_low_latency_js="false" ;;
  *) default_dynamic_low_latency_js="true" ;;
esac

default_dynamic_low_latency_hold_ms="${DEFAULT_DYNAMIC_LOW_LATENCY_HOLD_RAW}"
if ! [[ "$default_dynamic_low_latency_hold_ms" =~ ^[0-9]+$ ]] || [ "$default_dynamic_low_latency_hold_ms" -lt 300 ] || [ "$default_dynamic_low_latency_hold_ms" -gt 30000 ]; then
  default_dynamic_low_latency_hold_ms="15000"
fi

case "$DEFAULT_DYNAMIC_THROTTLE_MODE_RAW" in
  idle-low-bandwidth|idle-low-framerate|idle-low-occupancy) default_dynamic_throttle_mode="$DEFAULT_DYNAMIC_THROTTLE_MODE_RAW" ;;
  bandwidth|low-bandwidth) default_dynamic_throttle_mode="idle-low-bandwidth" ;;
  framerate|low-framerate) default_dynamic_throttle_mode="idle-low-framerate" ;;
  *) default_dynamic_throttle_mode="idle-low-occupancy" ;;
esac

default_dynamic_low_latency_fps="${DEFAULT_DYNAMIC_LOW_LATENCY_FPS_RAW}"
if ! [[ "$default_dynamic_low_latency_fps" =~ ^[0-9]+$ ]] || [ "$default_dynamic_low_latency_fps" -lt 1 ] || [ "$default_dynamic_low_latency_fps" -gt 120 ]; then
  default_dynamic_low_latency_fps="8"
fi

default_dynamic_low_latency_crf="${DEFAULT_DYNAMIC_LOW_LATENCY_CRF_RAW}"
if ! [[ "$default_dynamic_low_latency_crf" =~ ^[0-9]+$ ]] || [ "$default_dynamic_low_latency_crf" -lt 5 ] || [ "$default_dynamic_low_latency_crf" -gt 60 ]; then
  default_dynamic_low_latency_crf="35"
fi

default_dynamic_low_latency_sample="${DEFAULT_DYNAMIC_LOW_LATENCY_SAMPLE_RAW}"
if ! [[ "$default_dynamic_low_latency_sample" =~ ^[0-9]+$ ]] || [ "$default_dynamic_low_latency_sample" -lt 10 ] || [ "$default_dynamic_low_latency_sample" -gt 100 ]; then
  default_dynamic_low_latency_sample="87"
fi

default_stream_wait_threshold_ms="${DEFAULT_STREAM_WAIT_THRESHOLD_RAW}"
if ! [[ "$default_stream_wait_threshold_ms" =~ ^[0-9]+$ ]] || [ "$default_stream_wait_threshold_ms" -lt 10000 ] || [ "$default_stream_wait_threshold_ms" -gt 300000 ]; then
  default_stream_wait_threshold_ms="35000"
fi

default_stream_stall_threshold_ms="${DEFAULT_STREAM_STALL_THRESHOLD_RAW}"
if ! [[ "$default_stream_stall_threshold_ms" =~ ^[0-9]+$ ]] || [ "$default_stream_stall_threshold_ms" -lt 4000 ] || [ "$default_stream_stall_threshold_ms" -gt 120000 ]; then
  default_stream_stall_threshold_ms="18000"
fi

default_stream_stall_restart_limit="${DEFAULT_STREAM_STALL_RESTART_LIMIT_RAW}"
if ! [[ "$default_stream_stall_restart_limit" =~ ^[0-9]+$ ]] || [ "$default_stream_stall_restart_limit" -lt 1 ] || [ "$default_stream_stall_restart_limit" -gt 5 ]; then
  default_stream_stall_restart_limit="2"
fi

default_stream_recover_cooldown_ms="${DEFAULT_STREAM_RECOVER_COOLDOWN_RAW}"
if ! [[ "$default_stream_recover_cooldown_ms" =~ ^[0-9]+$ ]] || [ "$default_stream_recover_cooldown_ms" -lt 30000 ] || [ "$default_stream_recover_cooldown_ms" -gt 600000 ]; then
  default_stream_recover_cooldown_ms="120000"
fi

default_video_corruption_watchdog_js="true"
case "${DEFAULT_VIDEO_CORRUPTION_WATCHDOG_RAW,,}" in
  false|0|no|off) default_video_corruption_watchdog_js="false" ;;
  *) default_video_corruption_watchdog_js="true" ;;
esac

default_video_soft_recover_limit="${DEFAULT_VIDEO_SOFT_RECOVER_LIMIT_RAW}"
if ! [[ "$default_video_soft_recover_limit" =~ ^[0-9]+$ ]] || [ "$default_video_soft_recover_limit" -lt 1 ] || [ "$default_video_soft_recover_limit" -gt 5 ]; then
  default_video_soft_recover_limit="2"
fi

default_video_recover_cooldown_ms="${DEFAULT_VIDEO_RECOVER_COOLDOWN_RAW}"
if ! [[ "$default_video_recover_cooldown_ms" =~ ^[0-9]+$ ]] || [ "$default_video_recover_cooldown_ms" -lt 30000 ] || [ "$default_video_recover_cooldown_ms" -gt 600000 ]; then
  default_video_recover_cooldown_ms="120000"
fi

default_page_stall_watchdog_js="true"
case "${DEFAULT_PAGE_STALL_WATCHDOG_RAW,,}" in
  false|0|no|off) default_page_stall_watchdog_js="false" ;;
  *) default_page_stall_watchdog_js="true" ;;
esac

default_page_stall_threshold_ms="${DEFAULT_PAGE_STALL_THRESHOLD_RAW}"
if ! [[ "$default_page_stall_threshold_ms" =~ ^[0-9]+$ ]] || [ "$default_page_stall_threshold_ms" -lt 10000 ] || [ "$default_page_stall_threshold_ms" -gt 300000 ]; then
  default_page_stall_threshold_ms="45000"
fi

default_page_stall_reload_threshold_ms="${DEFAULT_PAGE_STALL_RELOAD_THRESHOLD_RAW}"
if ! [[ "$default_page_stall_reload_threshold_ms" =~ ^[0-9]+$ ]] || [ "$default_page_stall_reload_threshold_ms" -lt 30000 ] || [ "$default_page_stall_reload_threshold_ms" -gt 600000 ]; then
  default_page_stall_reload_threshold_ms="90000"
fi

default_page_stall_cooldown_ms="${DEFAULT_PAGE_STALL_COOLDOWN_RAW}"
if ! [[ "$default_page_stall_cooldown_ms" =~ ^[0-9]+$ ]] || [ "$default_page_stall_cooldown_ms" -lt 60000 ] || [ "$default_page_stall_cooldown_ms" -gt 1800000 ]; then
  default_page_stall_cooldown_ms="300000"
fi

default_render_stall_watchdog_js="true"
case "${DEFAULT_RENDER_STALL_WATCHDOG_RAW,,}" in
  false|0|no|off) default_render_stall_watchdog_js="false" ;;
  *) default_render_stall_watchdog_js="true" ;;
esac

default_render_stall_threshold_ms="${DEFAULT_RENDER_STALL_THRESHOLD_RAW}"
if ! [[ "$default_render_stall_threshold_ms" =~ ^[0-9]+$ ]] || [ "$default_render_stall_threshold_ms" -lt 5000 ] || [ "$default_render_stall_threshold_ms" -gt 120000 ]; then
  default_render_stall_threshold_ms="12000"
fi

default_render_stall_cooldown_ms="${DEFAULT_RENDER_STALL_COOLDOWN_RAW}"
if ! [[ "$default_render_stall_cooldown_ms" =~ ^[0-9]+$ ]] || [ "$default_render_stall_cooldown_ms" -lt 8000 ] || [ "$default_render_stall_cooldown_ms" -gt 300000 ]; then
  default_render_stall_cooldown_ms="25000"
fi

default_audio_watchdog_js="true"
case "${DEFAULT_AUDIO_WATCHDOG_RAW,,}" in
  false|0|no|off) default_audio_watchdog_js="false" ;;
  *) default_audio_watchdog_js="true" ;;
esac

default_audio_start_interval_ms="${DEFAULT_AUDIO_START_INTERVAL_RAW}"
if ! [[ "$default_audio_start_interval_ms" =~ ^[0-9]+$ ]] || [ "$default_audio_start_interval_ms" -lt 2000 ] || [ "$default_audio_start_interval_ms" -gt 60000 ]; then
  default_audio_start_interval_ms="8000"
fi

default_audio_packet_stall_ms="${DEFAULT_AUDIO_PACKET_STALL_RAW}"
if ! [[ "$default_audio_packet_stall_ms" =~ ^[0-9]+$ ]] || [ "$default_audio_packet_stall_ms" -lt 5000 ] || [ "$default_audio_packet_stall_ms" -gt 120000 ]; then
  default_audio_packet_stall_ms="15000"
fi

default_idle_cleanup_minutes="${DEFAULT_IDLE_CLEANUP_MINUTES_RAW}"
if ! [[ "$default_idle_cleanup_minutes" =~ ^[0-9]+$ ]] || [ "$default_idle_cleanup_minutes" -lt 5 ] || [ "$default_idle_cleanup_minutes" -gt 240 ]; then
  default_idle_cleanup_minutes="20"
fi

default_adaptive_sleep_idle_seconds="${DEFAULT_ADAPTIVE_SLEEP_IDLE_RAW}"
case "$default_adaptive_sleep_idle_seconds" in
  60|900|1800|2700|3600) ;;
  *) default_adaptive_sleep_idle_seconds="3600" ;;
esac

local_link_open_js="true"
case "${LOCAL_LINK_OPEN_RAW,,}" in
  false|0|no|off) local_link_open_js="false" ;;
  *) local_link_open_js="true" ;;
esac

local_link_poll_interval_ms="${LOCAL_LINK_POLL_INTERVAL_RAW}"
if ! [[ "$local_link_poll_interval_ms" =~ ^[0-9]+$ ]] || [ "$local_link_poll_interval_ms" -lt 300 ] || [ "$local_link_poll_interval_ms" -gt 10000 ]; then
  local_link_poll_interval_ms="800"
fi

dri_available_js="false"
if [ -e "$DRI_NODE_PATH" ] || [ -e "/dev/dri/renderD128" ] || [ -d "/dev/dri" ]; then
  dri_available_js="true"
fi

default_encoder="$(echo "$DEFAULT_ENCODER_RAW" | tr '[:upper:]' '[:lower:]')"
if [ -z "$default_encoder" ] || [ "$default_encoder" = "auto" ]; then
  default_encoder="x264enc"
fi

# Keep stable, low-latency encoders only; unsupported injected options can black-screen.
case "$default_encoder" in
  x264enc|x264enc-striped|jpeg) ;;
  *) default_encoder="x264enc" ;;
esac

if [ "$default_encoder" = "x264enc-striped" ] || [ "$default_encoder" = "jpeg" ]; then
  default_use_cpu_js="true"
fi

encoder_mode="CPU"
if [ "$default_use_cpu_js" = "false" ] && [ "$dri_available_js" = "true" ]; then
  encoder_mode="VAAPI"
fi

cat > "$CONFIG_PATH" <<EOF
window.__SELKIES_PASTE_IMAGE__ = {
  enabled: ${enabled_js},
  maxBytes: ${max_bytes},
  autoPaste: ${auto_js}
};
EOF

cat > "$RUNTIME_CONFIG_PATH" <<EOF
window.__SELKIES_RUNTIME__ = {
  driAvailable: ${dri_available_js},
  preferredEncoder: "${default_encoder}",
  encoderMode: "${encoder_mode}",
  defaultFramerate: ${default_framerate},
  defaultUseCpu: ${default_use_cpu_js},
  defaultH264StreamingMode: ${default_h264_streaming_mode_js},
  defaultUsePaintOverQuality: ${default_use_paint_over_quality_js},
  defaultH264Crf: ${default_h264_crf},
  streamWaitThresholdMs: ${default_stream_wait_threshold_ms},
  streamStallThresholdMs: ${default_stream_stall_threshold_ms},
  streamStallRestartLimit: ${default_stream_stall_restart_limit},
  streamRecoverCooldownMs: ${default_stream_recover_cooldown_ms},
  videoCorruptionWatchdog: ${default_video_corruption_watchdog_js},
  videoSoftRecoverLimit: ${default_video_soft_recover_limit},
  videoRecoverCooldownMs: ${default_video_recover_cooldown_ms},
  pageStallWatchdog: ${default_page_stall_watchdog_js},
  pageStallThresholdMs: ${default_page_stall_threshold_ms},
  pageStallReloadThresholdMs: ${default_page_stall_reload_threshold_ms},
  pageStallCooldownMs: ${default_page_stall_cooldown_ms},
  renderStallWatchdog: ${default_render_stall_watchdog_js},
  renderStallThresholdMs: ${default_render_stall_threshold_ms},
  renderStallCooldownMs: ${default_render_stall_cooldown_ms},
  audioWatchdog: ${default_audio_watchdog_js},
  audioStartIntervalMs: ${default_audio_start_interval_ms},
  audioPacketStallMs: ${default_audio_packet_stall_ms},
  idleCleanupMinutes: ${default_idle_cleanup_minutes},
  adaptiveSleepIdleSeconds: ${default_adaptive_sleep_idle_seconds},
  localLinkOpenEnabled: ${local_link_open_js},
  localLinkPollIntervalMs: ${local_link_poll_interval_ms},
  defaultGamepadEnabled: ${default_gamepad_js},
  gamepadUiEnabled: ${default_gamepad_js},
  dynamicLowLatencyEnabled: ${default_dynamic_low_latency_js},
  dynamicLowLatencyHoldMs: ${default_dynamic_low_latency_hold_ms},
  dynamicThrottleMode: "${default_dynamic_throttle_mode}",
  dynamicLowLatencyFps: ${default_dynamic_low_latency_fps},
  dynamicLowLatencyH264Crf: ${default_dynamic_low_latency_crf},
  dynamicLowLatencySamplePercent: ${default_dynamic_low_latency_sample},
  defaultBinaryClipboard: ${default_binary_clipboard_js}
};
EOF

chmod 644 "$CONFIG_PATH"
chmod 644 "$RUNTIME_CONFIG_PATH"
